stages:
  - build
  - deploy
  - notify

variables:
  BE_IMAGE: be-app:$CI_COMMIT_SHORT_SHA
  CONTAINER_NAME: be-app

build:
  stage: build
  script:
    - docker build -t $BE_IMAGE .
  only:
    - release
  tags:
    - macbook

deploy:
  stage: deploy
  needs: [build]
  script:
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true
    - docker run -d
        --name $CONTAINER_NAME
        -p $SERVER_PORT:$SERVER_PORT
        --restart unless-stopped
        -e SPRING_PROFILES_ACTIVE=prod
        -e POSTGRES_URL=$POSTGRES_URL
        -e POSTGRES_USER=$POSTGRES_USER
        -e POSTGRES_PASS=$POSTGRES_PASS
        -e REDIS_HOST=$REDIS_HOST
        -e REDIS_PORT=$REDIS_PORT
        -e REDIS_PASS=$REDIS_PASS
        -e MAIL_HOST=$MAIL_HOST
        -e MAIL_PORT=$MAIL_PORT
        -e MAIL_USERNAME=$MAIL_USERNAME
        -e MAIL_PASSWORD=$MAIL_PASSWORD
        -e MAIL_FROM=$MAIL_FROM
        -e SERVER_ADDRESS=${SERVER_ADDRESS}
        -e SERVER_PORT=${SERVER_PORT}
        -e CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
        $BE_IMAGE
    - docker images be-app --format "{{.Tag}}" | grep -v $CI_COMMIT_SHORT_SHA | xargs -I {} docker rmi be-app:{} || true
  only:
    - release
  tags:
    - macbook

notify-success:
  stage: notify
  needs: [deploy]
  script:
    - |
      curl -X POST $SLACK_WEBHOOK_URL \
      -H 'Content-type: application/json' \
      --data "{
        \"text\": \"✅ *BE Deploy Successful*\n- Branch: $CI_COMMIT_REF_NAME\n- Commit: $CI_COMMIT_SHORT_SHA\n- By: $CI_COMMIT_AUTHOR\n- URL: http://localhost:$SERVER_PORT\"
      }"
  only:
    - release
  tags:
    - macbook
  when: on_success

notify-failure:
  stage: notify
  script:
    - |
      curl -X POST $SLACK_WEBHOOK_URL \
      -H 'Content-type: application/json' \
      --data "{
        \"text\": \"❌ *BE Deploy failed*\n- Branch: $CI_COMMIT_REF_NAME\n- Commit: $CI_COMMIT_SHORT_SHA\n- By: $CI_COMMIT_AUTHOR\n- Pipeline: $CI_PIPELINE_URL\"
      }"
  only:
    - release
  tags:
    - macbook
  when: on_failure
